on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      skip_release:
        description: 'Skip release related steps? (true/false)'
        required: true
        default: 'false'

permissions:
  contents: write

env:
  version: m132-9b3c42e2f9-3

jobs:
  linux-arm64:
    runs-on: ubuntu-22.04-arm
    strategy:
      matrix:
        build_type: [ Release ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: addnab/docker-run-action@v3
        name: Build Skia
        id: assemble
        with:
            image: arm64v8/ubuntu:20.04
            # Mount checkout directory as /checkout in the container
            options: -v ${{ github.workspace }}:/checkout -e BUILD_TYPE=${{ matrix.build_type }} -e BUILD_VERSION=${{ env.version }} 
            # The shell to run commands with in the container
            shell: /bin/bash
            run: |
              cd /checkout
              echo $BUILD_TYPE $BUILD_VERSION
              /bin/bash script/prepare_linux_arm.sh
              python3 script/checkout.py --version $BUILD_VERSION

