on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      skip_release:
        description: 'Skip release related steps? (true/false)'
        required: true
        default: 'false'

permissions:
  contents: write

env:
  version: m132-9b3c42e2f9-3

jobs:
  linux-arm64:
    runs-on: ubuntu-22.04-arm
    strategy:
      matrix:
        build_type: [ Release ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: addnab/docker-run-action@v3
        name: Build Skia
        id: assemble
        with:
            image: arm64v8/ubuntu:20.04
            githubToken: ${{ secrets.GITHUB_TOKEN }}
            # Mount checkout directory as /checkout in the container
            options: -v ${{ github.workspace }}:/checkout
            envVars: |
              build_type: ${{ matrix.build_type }}
              build_version: ${{ env.version }}
              artifact_name: Skia-${{ env.version }}-linux-${{ matrix.build_type }}-arm64.zip
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            # The shell to run commands with in the container
            shell: /bin/bash
            run: |
              cd /checkout
              /bin/bash script/prepare_linux_arm.sh
              python3 script/check_release.py --version ${build_version} --build-type ${build_type}
              python3 script/checkout.py --version ${build_version}
              python3 script/build.py --build-type ${build_type}
              python3 script/archive.py --version ${build_version} --build-type ${build_type}
              echo "Produced artifact at ${PWD}/${artifact_name}"
              apt-get install -q -y bash

